"# Final Exam AIDI 2004 - Larissa Statton-Persad" 
"" 
"class TaskManager:" 
"    def addTask(self, title, priority):" 
"        pass" 
"    def deleteTask(self, task_id):" 
"        pass" 
"    # Deletes a task by its ID" 
"    def deleteTask(self, task_id):" 
"        return task_id" 
